SEAME-pt/Team04

- .github/workflows/bazel_build.yml
Add github action to run command bazel build with wildcard.
> ci: setup github action for bazel build

- docs/proposals/ADR_Build_System.md
Issue: https://github.com/SEAME-pt/jet_racers/issues/30
> docs: ADR for the build system

- .github/workflows/gitlint.yml
Linter to check git commits
Issue: https://github.com/SEAME-pt/jet_racers/issues/32
> ci: add gitlint

- .github/workflows/check_pr_description.yml
Add job to check if PR description contains link to issue.
Issue: https://github.com/SEAME-pt/jet_racers/issues/33
> ci: add job to check if PR has issue in description

- docs/proposals/ADR_cpp_compiler.md
Issue: https://github.com/SEAME-pt/jet_racers/issues/35
> doc: add ADR for cpp compiler

- .github/workflows/bazel_build.yml
- .github/workflows/bazel_test.yml
- .github/workflows/check_pr_description.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/gitlint.yml
- .github/workflows/yamllint.yml
Job fails if any error or warning in yaml files
Issue: https://github.com/SEAME-pt/jet_racers/issues/34
> ci: add yammlint job

- .github/workflows/clang_tidy.yml
- .github/workflows/yamllint.yml
Issue: https://github.com/SEAME-pt/jet_racers/issues/39
> ci: block merging PRs if jobs fail

- .github/workflows/bazel_build.yml
- .github/workflows/bazel_buildifier.yml
- .github/workflows/bazel_test.yml
- .github/workflows/yamllint.yml
The names are used to define the rule that blocks merges
Issues: https://github.com/SEAME-pt/jet_racers/issues/38
> ci: update actions names

- README.md
Add information about clang-format and bazel buildifier.
> docs: update tooling section in readme

- .github/workflows/yamllint.yml
- .gitignore
Issue: https://github.com/SEAME-pt/jet_racers/issues/43
> fix: wrong skip in yamlint workflow

- .github/pull_request_template.md
- .gitlint
> ci: ignore rule gitlint and add PR template

- .github/pull_request_template.md
- Add link to backlog
- Issue: https://github.com/SEAME-pt/jet_racers/issues/44
> ci: improve pr template

- .dockerignore
- .gitignore
- Dockerfile
- README.md
- WORKSPACE
Project runs in docker.
Instructions added in the Development Environment section of the documentation.
- Locally by creating image, running docker and running examples. The qt examples ran successfully with a window being open as expected.
- Issue: https://github.com/SEAME-pt/jet_racers/issues/45
> docker: make project run in docker

- README.md
- Add Jetson nano setup section to documentation.
- Issue: https://github.com/SEAME-pt/Team04/issues/43
> docs: add jetson setup

- docs/proposals/ADR_Monorepo_Architecture.md
- docs/proposals/ADR_Polyrepo_Architecture.md
- ADR for mono repo vs submodules 
- Link to the related GitHub issue (<https://github.com/SEAME-pt/Team04/issues/46>).
> docs: Add polyrepo and monorepo ADR proposals

- docs/proposals/ADR_Naming_Conventions.md
- Create ADR naming conventions proposal
- Link to the related GitHub issue (<https://github.com/SEAME-pt/Team04/issues/47>).
- The team need to discuss the options
> Create ADR naming conventions proposal

- .bazelrc
- .clang-tidy
- .github/workflows/bazel_build.yml
- .github/workflows/bazel_buildifier.yml
- .github/workflows/bazel_test.yml
- .github/workflows/clang_format.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/yamllint.yml
- Dockerfile
- README.md
Run or skip workflows based on changed files.
Issue: https://github.com/SEAME-pt/Team04/issues/39
> ci: make actions incremental and using docker image

- .github/workflows/arduino_lint.yml
- Dockerfile
- Add job to run arduino-lint
Running action in CI.
Issue: https://github.com/SEAME-pt/jet_racers/issues/58
> ci: add arduino-lint github action

- .github/workflows/gitlint.yml
- Dockerfile
Run gitlint action inside custom docker image.
Tested on the CI.
> ci: make gitlint action run in docker image

- Dockerfile
Add zmq to Dockerfile and updated image was pushed.
Tested locally.
> Tooling: add zmq to docker image

- .devcontainer/devcontainer.json
- Dockerfile
- config/ubuntu.sources
- Adding library for cross compilation in arm
- Tested locally and in CI
#82
> feat: add arm cross compile libraries

- .github/workflows/arduino_lint.yml
- .github/workflows/bazel_build_aarch64.yml
- .github/workflows/bazel_build_x86.yml
- .github/workflows/bazel_buildifier.yml
- .github/workflows/bazel_test.yml
- .github/workflows/clang_format.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/coverage.yml
- .github/workflows/gitlint.yml
- .github/workflows/sanitizers.yml
- .github/workflows/yamllint.yml
- README.md
Update the docker image used by github actions.
CI actions.
Issue: https://github.com/SEAME-pt/Team04/issues/113
> ci: update docker image used by github actions

- README.md
Update documentation by adding how to copy files from container information.
Issue: https://github.com/SEAME-pt/Team04/issues/50
> docs: add information on how to copy files from docker container

- examples/baseCar/BUILD
- examples/baseCar/main.cpp
- platform/carMove/BUILD
- platform/carMove/carMove.cpp
- platform/carMove/carMove.hpp
- platform/joystick/BUILD
- platform/joystick/joystick.cpp
- platform/joystick/joystick.hpp
- Add libs for car movement and joystick controling in cpp.
- Add example of usage.
- Will be tested on HW
Issue: https://github.com/SEAME-pt/Team04/issues/81
Issue: https://github.com/SEAME-pt/Team04/issues/78
> feat: carmove and joystick libs implementation

- .clang-format
- .clang-tidy
- .github/workflows/bazel_build_aarch64.yml
- .github/workflows/bazel_build_x86.yml
- .github/workflows/docker_push.yml
- README.md
- examples/baseCar/main.cpp
- examples/gpio_sdl/gpio_sdl.cpp
- examples/gpio_sdl/main.cpp
- platform/joystick/joystick.cpp
- Improve documentation by adding `bazel cache` information.
- Update clang-tidy configuration.
- Update cpp  code to comply with new clang-tidy config.
- Build github actions run for all targets if any bazel file is changed.
- Remove redundant docker push action periodic trigger, it is only necessary to push when Dockerfile is changed.
This is done to block breaking changes from being introduced.
The `clang-tidy` and `clang-format` config can be revise in the future.
Tested locally and CI.
There is no universal `clang-tidy` config, so I copied the configuration from the [Carbon repo](https://github.com/carbon-language/carbon-lang/blob/trunk/.clang-tidy), since probably the google people know what they are doing.
> miscellaneous: improve tooling, docs and ci

- .github/workflows/coverage.yml
- Dockerfile
- examples/cpp/test.cpp
- tools/coverage/README.md
- tools/coverage/lcov.sh
Update coverage script to enable baseline.
Locally and on coverage CI action.
```bash
bazel run //tools/coverage:lcov -- -t <test_target> -b <baseline_target> -o <output_dir> -c $(bazel info bazel-bin) -d $(bazel info bazel-testlogs)
```
Issue: https://github.com/SEAME-pt/Team04/issues/110
> coverage: create coverage report with baseline

- docs/carmotion.md
- docs/joystick.md
- examples/baseCar/main.cpp
- platform/carMove/carMove.cpp
- platform/carMove/carMove.hpp
- platform/joystick/joystick.cpp
- platform/joystick/joystick.hpp
Fix wrong movements
Include documentation for carMove and joystick classes
Create new method in joystick car to allow mapping pressed buttons 
- in Raspberry
https://github.com/SEAME-pt/Team04/issues/78
> fix: classes improved and docs

- docs/ethernet.md
Documentation for the ethernet connection process and describing the performed tests. resolves #131 
Tested locally
#131
> doc: added documentation for ethernet connection process

- .github/workflows/release.yml
- BUILD
- MODULE.bazel
- README.md
- bazel/rules/qt.bzl
- com-middleware/BUILD
- examples/BUILD
- examples/baseCar/BUILD
- examples/cpp/BUILD
- examples/gpio_sdl/BUILD
- examples/qt/qml/BUILD
- examples/qt/ui/BUILD
Include a tar package with binaries for releases.
A release was created with the bins: https://github.com/SEAME-pt/Team04/releases/tag/v1.0.0
Issue: https://github.com/SEAME-pt/Team04/issues/142
References: https://github.com/bazelbuild/rules_pkg/tree/main
> release: add tar with binaries

- tools/coverage/lcov.sh
Ignore coverage files of all files that contain test in the path.
Coverage github action.
> coverage: dont collect coverage of test files

- instrument-cluster/main.cpp
- instrument-cluster/mq/ZMQSubscriber.cpp
- mq/src/IMQSocket.hpp
- mq/src/ZeroMQSocket.cpp
- mq/src/ZeroMQSocket.hpp
- mq/src/ZeroMQWorker.cpp
- mq/src/ZeroMQWorker.hpp
- mq/test/ZeroMQSocketTest.cpp
- mq/test/ZeroMQWorkerTest.cpp
feature: mq library returns optional for better error handling; handling signals on Instrument Cluster
- Tested locally and w/ unit tests
#85 
N/A
> feat: returning optional on mq receive, handling signals on IC

- .github/workflows/arduino_lint.yml
- .github/workflows/bazel_build_aarch64.yml
- .github/workflows/bazel_build_x86.yml
- .github/workflows/bazel_buildifier.yml
- .github/workflows/bazel_test.yml
- .github/workflows/clang_format.yml
- .github/workflows/clang_tidy.yml
- .github/workflows/coverage_deploy.yml
- .github/workflows/coverage_summary.yml
- .github/workflows/docker_build.yml
- .github/workflows/docker_push.yml
- .github/workflows/release.yml
- .github/workflows/sanitizers.yml
- .github/workflows/yamllint.yml
Rebase PR branch with main to run github action.
Tested running actions.
Issue: https://github.com/SEAME-pt/Team04/issues/152
N/A
> ci: run actions on PR branch rebased with main

- com-middleware/src/main.cpp
- instrument-cluster/mq/ZMQSubscriber.cpp
- instrument-cluster/mq/ZMQSubscriber.hpp
- Adding message to zeromq message to support different types
- Tested locally, unit tested
#85 
N/A
> feat: add id to mq message

- com-middleware/src/main.cpp
- instrument-cluster/Main.qml
- instrument-cluster/main.cpp
- instrument-cluster/mq/ZMQSubscriber.cpp
- instrument-cluster/qml/ClusterData/Backend.qml
- instrument-cluster/src/DataManager.cpp
- instrument-cluster/src/DataManager.hpp
- mq/src/ZeroMQSocket.cpp
- mq/src/ZeroMQWorker.cpp
- mq/src/ZeroMQWorker.hpp
- mq/test/ZeroMQWorkerTest.cpp
- platform/battery-sensor/BUILD
- platform/battery-sensor/main.cpp
- platform/temperature-sensor/BUILD
- platform/temperature-sensor/main.cpp
- Base implementation of battery and temperature sensor services
- Tested locally
#134 
N/A
> feat: base for battery and temp services

- .github/workflows/coverage_compare.yml
- Check if bot comment with coverage values exists and update it with new coverage values.
- In this PR by making action post a [comment and updated it](https://github.com/SEAME-pt/Team04/pull/171#issuecomment-2651000217)
Issue: https://github.com/SEAME-pt/Team04/issues/169
N/A
> coverage: update previous github actions PR comment

- docs/autonomous_driving/lane_detection.md
- Add documentation with information about lane detection dataset and state of the art methods.
- A more detail research can be done on a follow-up.
- N/A.
Issue: https://github.com/SEAME-pt/Team04/issues/168
Issue: https://github.com/SEAME-pt/Team04/issues/175
- Number of citations in tables are according to Google Scholar.
> docs: add lane detection datasets and methods information

- docs/autonomous_driving/control.md
- Add documentation about control methods for lane keeping.
- Documentation includes the steps of a proposed approach for lane keeping using image based model predictive control.
Issue: https://github.com/SEAME-pt/Team04/issues/181
- Further improvements can be added on follow-up.
> docs: control methods for lane keeping
