.clang-tidy
.github/workflows/bazel_build.yml
.github/workflows/bazel_test.yml
.github/workflows/clang_tidy.yml
examples/cpp/hello.cpp
examples/cpp/hello.hpp
examples/cpp/main.cpp

Problem with including gtest, clang-tidy throws error.
Bazel doesnt allow to create compilation database.
Easiest solution is to ignore test files, and dont run clang-tidy on test files (regex `test*.cpp`).

ci: add clang tidy

---

.bazelrc
.clang-tidy
examples/cpp/main.cpp

Warnings options added in .bazelrc.
Warnings treated as errors.
`third_party` and `external` where excluded.
The implementation of [bazel features](https://bazel.build/docs/cc-toolchain-config-reference) can be investigated on a follow-up.

bazel: add warning options and treat warnings as errors

---

.bazelrc
.clang-tidy
.github/workflows/clang_tidy.yml
BUILD
MODULE.bazel
README.md
WORKSPACE
examples/cpp/hello.hpp
examples/cpp/test.cpp

A compile commands file can be used so that clang tidy has access to the information related to the build.
With this approach, clang-tidy can solve the includes of the external dependencies, such as qt or gtest.
The compiler was changed to clang, so that the warning options would be compatible with clang-tidy.
The C++ version was defined as 20. gtest is incompatible with C++23.
Issue: https://github.com/SEAME-pt/jet_racers/issues/29

ci: run clang-tidy with compile commands option

---

.github/workflows/bazel_buildifier.yml

Run buildifier only if bazel files where changed, else report as success.
Required for blocking merges.

ci: make bazel buildifier job incremental

---

WORKSPACE
examples/qt/BUILD
examples/qt/README
examples/qt/hello.cpp
examples/qt/hello.hpp
examples/qt/main.cpp

Qt is hermetic, meaning it automatically downloads.
How to run example:
```bash
bazel run //examples/qt:bin
```
Issue: https://github.com/SEAME-pt/jet_racers/issues/28

bazel: add support for qt with hello world example

---

.clang-format
.github/workflows/clang_format.yml
examples/cpp/hello.cpp
examples/cpp/main.cpp
examples/cpp/test.cpp
examples/qt/hello.cpp
examples/qt/hello.hpp
examples/qt/main.cpp

clang-format is configured accordingly to the .clang-format file.
More options can be added to the .clang-format file in a follow-up.
Issue: https://github.com/SEAME-pt/jet_racers/issues/36

ci: add clang-format workflow

---

.github/workflows/bazel_buildifier.yml
.github/workflows/clang_format.yml
.github/workflows/clang_tidy.yml

Split string and iterate through files
Issue: https://github.com/SEAME-pt/jet_racers/issues/43

fix: condition for job skipping

---

.github/workflows/bazel_buildifier.yml

The file variable contains the full path so matching with `*`
Issue: https://github.com/SEAME-pt/jet_racers/issues/43

ci: fix condition in buildifier workflow

---

README.md

ci: update readme with how to setup bazel

---

.bazelrc
README.md
examples/cpp/BUILD

Non-critical code doesn't need to comply with `-Weverything`.
Default options changed.
Build workflow.

tool: change default warning options

---

.github/workflows/llvm_cov.yml
tools/coverage/BUILD
tools/coverage/README.md
tools/coverage/llvm_cov.sh

Add shell script to generate coverage report and add github action to run script.
This is the initial implementation, improve will be added on follow-ups.
On a follow-up:
- Create report with baseline
- Make job incremental
- If coverage drops, block PR
How to Run:
```bash
bazel run //tools/coverage:llvm_cov -- -t <test_target>
```
Issue: https://github.com/SEAME-pt/Team04/issues/38

coverage: add initial implementation of llvm-cov

---

.github/workflows/check_pr_description.yml

Extend pattern to also allow to linking issues that start with `#`.
Running action in CI.
[#38](https://github.com/SEAME-pt/jet_racers/issues/38)

ci: extend pattern in github action to check github description

---

.github/workflows/arduino_lint.yml

Fix for arduino linter action, by adding `--recursive` option.
Tested on the CI.

ci: run arduino-lint recursively across the arduino directory

---

arduino/speed_receive/speed_receive.ino
arduino/speed_send/speed_send.ino
docs/communication.md

- feature: added arduino code to send speed data via CAN BUS
This code was tested with two arduinos according to the following schematic:
Note that the CAN sender was used with the seeed CAN-BUS 2.0 and as such the code works as is. If a MCP2515 module is used, the clock rate needs to be changed to 8Mhz.
Issue: #62 
- The CAN message was defined with a byte representing the speed and two bytes (word) representing the RPM. This might change if needed.

Added module for sending speed sensor data via CAN Bus

---

.github/workflows/arduino_lint.yml
.github/workflows/bazel_build.yml
.github/workflows/bazel_buildifier.yml
.github/workflows/bazel_test.yml
.github/workflows/check_pr_description.yml
.github/workflows/clang_format.yml
.github/workflows/clang_tidy.yml
.github/workflows/gitlint.yml
.github/workflows/llvm_cov.yml
.github/workflows/sanitizers.yml
.github/workflows/yamllint.yml
README.md
toolchain/aarch64_linux/cc_toolchain_config.bzl
toolchain/x86_64_linux/cc_toolchain_config.bzl

Add job to run ASAN, UBSAN and TSAN on affected targets by changes  on cpp targets, excluding test targets.
Tested by running github actions in CI.
Issue: https://github.com/SEAME-pt/Team04/issues/42

ci: add sanitizers github action

---

.github/workflows/clang_tidy.yml
MODULE.bazel
README.md
bazel/rules/qt.bzl
examples/qt/BUILD
examples/qt/README
examples/qt/main.cpp
examples/qt/mainwindow.cpp
examples/qt/mainwindow.h
examples/qt/mainwindow.ui

Different files need be generated to enable full Qt functionality.
Custom Bazel rules were added that create `cc_libs` and `cc_bins` and to call genrules for file generation.
The proposed implementation also complies with x86 and aarch64 by allowing linking to different libs.
This is also a required step for upgrading to Qt6.
The custom rules improve the quality of life of the developers and avoid a lot of duplication.
Improved example/qt and tested locally.
Tested by building and running on x86 with:
```bash
bazel run //examples/qt:bin
```
and cross-compiled for aarch64:
```bash
bazel build //examples/qt:bin --platforms=//bazel/platforms:aarch64_linux
```
Issue: https://github.com/SEAME-pt/Team04/issues/99
References:
- https://github.com/Vertexwahn/rules_qt6
- …

toolchain: add custom rules for Qt integration

---

.github/workflows/bazel_build_aarch64.yml
.github/workflows/bazel_build_x86.yml

Add action to ensure that code compiles for `aarch64` so that no breaking changes are introduced on main.
Tested on the CI.
Issue: https://github.com/SEAME-pt/Team04/issues/102

ci: add github action to build for aarch64

---

.github/workflows/coverage.yml
README.md
examples/BUILD

- Added a test suite to support coverage reporting.
- Updated the documentation to include detailed instructions on how to add tests for coverage, including best practices for organizing tests and integrating them into the `unit_tests` suite.
Tested locally, by generating a coverage report with:
```bash
bazel run //tools/coverage:lcov -- -t :unit_tests
```
and CI github action.
Issue: https://github.com/SEAME-pt/Team04/issues/106
To do on a follow-up task:
- Generate coverage report with baseline.
- Gating mechanism for coverage.

coverage: define test suite with unit tests

---

Dockerfile

Updated docker image configuration with:
- Base image Ubuntu 24.04
- `gcc-14`
Also reorganized the Dockerfile for better structure.
Tested locally and on the CI running github actions.
Issue: https://github.com/SEAME-pt/Team04/issues/104
`gcc-14` package is [not available for Ubuntu 22.04](https://askubuntu.com/a/1513162).

tooling: update docker image to use gcc-14 and ubuntu 24.04

---

Dockerfile

libsdl2 and pigpio are required to control the car.
pigpio is build from source for x86.
aarch64 implementation will be done on a follow-up.
Tested locally and on the CI.
Issue: https://github.com/SEAME-pt/Team04/issues/81
- https://wiki.libsdl.org/SDL2/Installation
- https://github.com/joan2937/pigpio
- https://abyz.me.uk/rpi/pigpio/pigpiod.html

docker: add libsdl2 and pigpio x86

---

.github/workflows/docker.yml

Add action to build and push DOCKERFILE, that triggers if changes in DOCKERFILE are merged and everyday at midnight. 
Tested on the CI changing action to trigger on branch push.
Issue: https://github.com/SEAME-pt/Team04/issues/113
After merge, image used by other github actions is going to be changed on follow-up PR.
Docker hub: https://hub.docker.com/r/t4seame/app

ci: automate docker build and push

---

.github/workflows/docker.yml
.github/workflows/release.yml
README.md

Add github action that creates release triggered by tag.
Created a release: https://github.com/SEAME-pt/Team04/releases/tag/v1.0.0
Issue: https://github.com/SEAME-pt/Team04/issues/119
Commands used to create release:
```bash
git tag v1.0.0
```
```bash
git push origin v1.0.0
```

ci: automate releases

---

Dockerfile

- Downgrading gcc to 12 for cross compilation
- Locally
#82

downgrading to gcc-12 for cross compilation compatibility

---

Dockerfile
README.md
bazel/rules/qt.bzl

Update toolchain to use qt6.
Tested locally.
Issue: https://github.com/SEAME-pt/Team04/issues/96
This also fixes failure caused by missing `libxcb.so` when trying to run aarch64 binaries on x86.
So now its possible to run and display arm64 bin s locally on x86, with the following command:
```bash
bazel run //examples/qt:bin --platforms=//bazel/platforms:aarch64_linux
```

toolchain: update to qt6

---

Dockerfile
examples/gpio_sdl/BUILD
examples/gpio_sdl/README
examples/gpio_sdl/gpio_sdl.cpp
examples/gpio_sdl/gpio_sdl.h
examples/gpio_sdl/main.cpp
toolchain/aarch64_linux/cc_toolchain_config.bzl
toolchain/x86_64_linux/cc_toolchain_config.bzl
tools/cross_compilation/pigpio/makefile

Add [SDL2](https://wiki.libsdl.org/SDL2/Installation) and [pigpio](https://abyz.me.uk/rpi/pigpio/download.html) to toolchain.
Adding `SDL2` is straightforward however `pigpio` required compiling from source for both `x86` and `arm64`.
Able to cross-compile and bins run on target.
Issue: https://github.com/SEAME-pt/Team04/issues/125
The makefile is mainly identical to the one from [pigpio repo](https://github.com/joan2937/pigpio/blob/master/Makefile).
This PR uses temporary solution to get cross-compilation working, that is finding and copying pigpio files.
There is a problem setting the [destination path](https://github.com/joan2937/pigpio/issues/36) on the official makefile. A follow-up will improve this implementation.

toolchain: add SDL2 and pigpio

---

bazel/rules/qt.bzl

Include Qt6 headers as systems includes since those are external headers in which we want to suppress warnings.
Compiled qml example with critical warnings features.
```bash
qt_cc_binary(
name = "bin",
srcs = ["main.cpp"],
features = ["warnings_critical_code_gcc"],
deps = [
":qrc",
],
)
```
```bash
bazel run //examples/qt/qml:bin
```

toolchain: Add Qt6 directories to list of system include paths

---

.github/workflows/coverage_deploy.yml
.github/workflows/coverage_summary.yml
.github/workflows/docker_push.yml
README.md
tools/coverage/lcov.sh

Automate coverage reporting via github pages.
Reports source code of relevant targets, `cc_bins` and `cc_libs` that are flashed to car.
Report uploaded to [github page](https://seame-pt.github.io/Team04/).
Issue: https://github.com/SEAME-pt/Team04/issues/141
Scope of what we intend to include in the coverage report, which `cc_bins` and `cc_libs`, will be further discussed.

ci: deploy github pages with coverage report

---

tools/coverage/lcov.sh

Ignore errors caused by external sources not found during baseline creation.
Error can be ignore since it is not intended to gather coverage for external source.
Locally.

fix: coverage no source error in baseline

---

.github/workflows/release.yml
README.md

Include both x86 and arm64 bins in releases.
Created a new release: https://github.com/SEAME-pt/Team04/releases/tag/v1.0.0

ci: add aarch64 and x86 bins to release

---

.github/workflows/coverage_deploy.yml
.github/workflows/coverage_summary.yml
BUILD
README.md
com-middleware/BUILD
examples/BUILD
instrument-cluster/BUILD
tools/coverage/lcov.sh

- Improve project organization by adding a filegroup at root with the bins for target.
- Use the new filegroup to create coverage baseline.
- Dont include qt generate files in the coverage report.
Coverage report generated: https://seame-pt.github.io/Team04/

coverage: create baseline with filegroup of cc_bins

---

.github/workflows/release.yml
BUILD
platform/BUILD
platform/battery-sensor/BUILD
platform/temperature-sensor/BUILD

- Remove auto rebase with main for release.
- Include `platform/battery-sensor` and `platform/temperature-sensor` binaries  in releases and coverage report.
CI.
- See updated github page: https://seame-pt.github.io/Team04/

bazel: add platform bins to root filegroup

---

arduino/speed_receive/speed_receive.ino
arduino/speed_send/speed_send.ino
com-middleware/src/main.cpp
docs/communication.md
instrument-cluster/Main.qml
instrument-cluster/main.cpp
instrument-cluster/mq/ZMQSubscriber.cpp
instrument-cluster/mq/ZMQSubscriber.hpp
instrument-cluster/qml/ClusterData/Backend.qml
instrument-cluster/src/DataManager.cpp
instrument-cluster/src/DataManager.hpp
mq/src/ZeroMQSocket.cpp
platform/battery-sensor/main.cpp
platform/speed-simulator/BUILD
platform/speed-simulator/main.cpp

- Changed speed and rpm to floats. The can message of 8 bytes now contain only the speed and rpm in each 4 bytes.
- Changed instrument cluster to handle new message format
- Created a speed simulator for seeing real time changes
- Tested locally
#85 
N/A

feat: changing speed and rpm to floats

---

third_party/python/requirements.txt

- Add numpy, scipy, matplotlib and opencv python packages.
- See this [example](https://github.com/SEAME-pt/Team04/blob/2d312a704ad4f346457d5396a1f858ee4d08aca0/tools/coverage/utils/BUILD#L1) for adding a package dependency in the BUILD file.
- Tested locally running simple example.
Issue: https://github.com/SEAME-pt/Team04/issues/192
Python package repository: https://pypi.org

toolchain: add python packages required for lane detection
